services:
  db:
    image: postgres:15
    container_name: sms_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sms_db
    ports:
      - "5439:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - sms-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sms_app
    depends_on:
      - db
    ports:
      - "9090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5439/sms_db
    networks:
      - sms-net

volumes:
  db-data:

networks:
  kazie-net: